# Generated by Django 4.0.3 on 2022-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('phone_numb', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('color', models.TextField()),
                ('birthday', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_offered', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_price', models.CharField(default='Price For service', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('pet', models.CharField(max_length=100)),
                ('day_of_appointment', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_confirmation', models.BooleanField(default=False)),
                ('services_available', models.ManyToManyField(to='pet_groomers.services')),
            ],
        ),
    ]
