# Generated by Django 4.1 on 2022-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_groomers', '0002_appointment_check_if_services_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='report',
            field=models.TextField(blank=True, default='Enter a report after the services', null=True),
        ),
    ]
