# Generated by Django 4.1 on 2022-09-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('based', '0002_alter_clientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientappointments',
            name='time_of_day',
            field=models.CharField(default='h/m', max_length=5),
        ),
    ]
